services:
  # 1. Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # 2. Backend FastAPI & AI Engine
  backend:
    build:
      context: .   # 🔥 FIX: Isay '.' rakha hai taake root wali requirements.txt mil jaye
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    depends_on:
      - db

  # 3. SQL Server Database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: deepguard_db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "AdminPassword123!"
    volumes:
      - sql_data:/var/opt/mssql
      - ./DeepGuard.sql:/DeepGuard.sql

volumes:
  sql_data: