# Base Node.js image
FROM node:18-alpine

WORKDIR /app

# Packages install karna
COPY package.json package-lock.json ./
RUN npm install

# Frontend ka code copy karna
COPY public/ ./public/
COPY src/ ./src/

# Port open karna
EXPOSE 3000

# React app start karna
CMD ["npm", "start"]